---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - database.cpf-it.fr
  resources:
  - mariadbhas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.cpf-it.fr
  resources:
  - mariadbhas/finalizers
  verbs:
  - update
- apiGroups:
  - database.cpf-it.fr
  resources:
  - mariadbhas/status
  verbs:
  - get
  - patch
  - update
