//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfig) DeepCopyInto(out *BackupConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfig.
func (in *BackupConfig) DeepCopy() *BackupConfig {
	if in == nil {
		return nil
	}
	out := new(BackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverConfig) DeepCopyInto(out *FailoverConfig) {
	*out = *in
	in.FailureDetection.DeepCopyInto(&out.FailureDetection)
	if in.MinimumIntervalSeconds != nil {
		in, out := &in.MinimumIntervalSeconds, &out.MinimumIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutomaticFailback != nil {
		in, out := &in.AutomaticFailback, &out.AutomaticFailback
		*out = new(bool)
		**out = **in
	}
	if in.ReadOnlyMode != nil {
		in, out := &in.ReadOnlyMode, &out.ReadOnlyMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverConfig.
func (in *FailoverConfig) DeepCopy() *FailoverConfig {
	if in == nil {
		return nil
	}
	out := new(FailoverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverEvent) DeepCopyInto(out *FailoverEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverEvent.
func (in *FailoverEvent) DeepCopy() *FailoverEvent {
	if in == nil {
		return nil
	}
	out := new(FailoverEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureDetectionConfig) DeepCopyInto(out *FailureDetectionConfig) {
	*out = *in
	if in.HealthCheckIntervalSeconds != nil {
		in, out := &in.HealthCheckIntervalSeconds, &out.HealthCheckIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FailureThresholdCount != nil {
		in, out := &in.FailureThresholdCount, &out.FailureThresholdCount
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.HealthChecks != nil {
		in, out := &in.HealthChecks, &out.HealthChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureDetectionConfig.
func (in *FailureDetectionConfig) DeepCopy() *FailureDetectionConfig {
	if in == nil {
		return nil
	}
	out := new(FailureDetectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceConfig) DeepCopyInto(out *InstanceConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Config.DeepCopyInto(&out.Config)
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceConfig.
func (in *InstanceConfig) DeepCopy() *InstanceConfig {
	if in == nil {
		return nil
	}
	out := new(InstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancesConfig) DeepCopyInto(out *InstancesConfig) {
	*out = *in
	in.Primary.DeepCopyInto(&out.Primary)
	in.Secondary.DeepCopyInto(&out.Secondary)
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancesConfig.
func (in *InstancesConfig) DeepCopy() *InstancesConfig {
	if in == nil {
		return nil
	}
	out := new(InstancesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConfig) DeepCopyInto(out *MariaDBConfig) {
	*out = *in
	if in.ConfigurationParameters != nil {
		in, out := &in.ConfigurationParameters, &out.ConfigurationParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UserCredentialsSecret != nil {
		in, out := &in.UserCredentialsSecret, &out.UserCredentialsSecret
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConfig.
func (in *MariaDBConfig) DeepCopy() *MariaDBConfig {
	if in == nil {
		return nil
	}
	out := new(MariaDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBHA) DeepCopyInto(out *MariaDBHA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBHA.
func (in *MariaDBHA) DeepCopy() *MariaDBHA {
	if in == nil {
		return nil
	}
	out := new(MariaDBHA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBHA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBHAList) DeepCopyInto(out *MariaDBHAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MariaDBHA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBHAList.
func (in *MariaDBHAList) DeepCopy() *MariaDBHAList {
	if in == nil {
		return nil
	}
	out := new(MariaDBHAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBHAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBHASpec) DeepCopyInto(out *MariaDBHASpec) {
	*out = *in
	in.Instances.DeepCopyInto(&out.Instances)
	in.Replication.DeepCopyInto(&out.Replication)
	in.Failover.DeepCopyInto(&out.Failover)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Backup.DeepCopyInto(&out.Backup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBHASpec.
func (in *MariaDBHASpec) DeepCopy() *MariaDBHASpec {
	if in == nil {
		return nil
	}
	out := new(MariaDBHASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBHAStatus) DeepCopyInto(out *MariaDBHAStatus) {
	*out = *in
	if in.LastFailoverTime != nil {
		in, out := &in.LastFailoverTime, &out.LastFailoverTime
		*out = (*in).DeepCopy()
	}
	if in.ReplicationLag != nil {
		in, out := &in.ReplicationLag, &out.ReplicationLag
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailoverHistory != nil {
		in, out := &in.FailoverHistory, &out.FailoverHistory
		*out = make([]FailoverEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBHAStatus.
func (in *MariaDBHAStatus) DeepCopy() *MariaDBHAStatus {
	if in == nil {
		return nil
	}
	out := new(MariaDBHAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.PrometheusExporter != nil {
		in, out := &in.PrometheusExporter, &out.PrometheusExporter
		*out = new(bool)
		**out = **in
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationConfig) DeepCopyInto(out *ReplicationConfig) {
	*out = *in
	if in.AutomaticFailover != nil {
		in, out := &in.AutomaticFailover, &out.AutomaticFailover
		*out = new(bool)
		**out = **in
	}
	if in.MaxLagSeconds != nil {
		in, out := &in.MaxLagSeconds, &out.MaxLagSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ReconnectRetries != nil {
		in, out := &in.ReconnectRetries, &out.ReconnectRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationConfig.
func (in *ReplicationConfig) DeepCopy() *ReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(ReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
